#!/bin/sh -e

# Fix wonky sbindir location.
export MOUNT_FUSE_PATH=/usr/bin

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-lib \
    --enable-util \
    --disable-example

make
make DESTDIR="$1" install

# Remove old init script.
rm -rf "$1/etc/init.d"
