#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Remove libcap dependency (used solely when bwrap is suid
# root). User namespaces are much better, should be used
# in place of libcap and are free.
sed -i 's/as_fn_error.*libcap/: "/g'          configure
sed -i 's/as_fn_error.*capability\.h/: "/g' configure

# Remove fuse2 dependency (used solely with root "system-helper"
# daemon for file transfer. Unneeded in our case and drops the
# old fuse version.
sed -i 's/as_fn_error.*fuse/: "/g' configure

# Turn the fuse2 filesystem into a C program which does nothing.
# This is the easiest way to "turn off" revokefs as there's
# no officials support for doing so.
cat <<EOF > revokefs/main.c
int main() { return 0; }
EOF
: > revokefs/writer.c

# Install python-pyparsing which is solely needed for
# flatpak and thus contained in this build.
{
    cd pyparsing

    python3 setup.py build
    python3 setup.py install \
        --prefix=/usr \
        --root="$PWD/dist"

    # Use a glob to avoid having to figure out the Python
    # version for the path below.
    cd dist/usr/lib/python*/site-packages

    # Set the PYTHONPATH so python knows where to find mako.
    # The one liner simply appends the existing path and
    # handles the case where an unset PYTHONPATH breaks
    # python as it will only contain our new addition.
    PYTHONPATH=$PWD:$(python -c "import sys; print(':'.join(sys.path))")

    cd -; cd ..
}

export PYTHONPATH

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --without-systemd \
    --disable-system-helper \
    --disable-nls \
    --disable-seccomp \
    --disable-sandboxed-triggers \
    --disable-documentation \
    --disable-introspection \
    --with-priv-mode=none

make
make DESTDIR="$1" install

# Remove dbus/systemd/libraries (unneeded stuff).
# This is a dumb warning which appears only when /usr/share does.
# shellcheck disable=2115
{
    rm -rf "$1/etc"
    rm -rf "$1/usr/share"
    rm -rf "$1/usr/lib"
    rm -rf "$1/usr/include"
    rm  -f "$1/usr/libexec/revokefs-fuse"
}
