#!/bin/sh -e

patch -p1 < fix-musl.patch
patch -p1 < bubblewrap-musl.patch

# Install python-pyparsing which is solely needed for
# flatpak and thus contained in this build.
{
    cd pyparsing

    python3 setup.py build
    python3 setup.py install \
        --prefix=/usr \
        --root="$PWD/dist"

    # Use a glob to avoid having to figure out the Python
    # version for the path below.
    cd dist/usr/lib/python*/site-packages

    # Set the PYTHONPATH so python knows where to find mako.
    # The one liner simply appends the existing path and
    # handles the case where an unset PYTHONPATH breaks
    # python as it will only contain our new addition.
    PYTHONPATH=$PWD:$(python -c "import sys; print(':'.join(sys.path))")

    cd -; cd ..
}

export PYTHONPATH

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --without-systemd \
    --disable-system-helper \
    --disable-seccomp \
    --disable-sandboxed-triggers \
    --disable-documentation \
    --with-priv-mode=none

make
make DESTDIR="$1" install

# Remove dbus/systemd/libraries (unneeded stuff).
# This is a dumb warning which appears only when /usr/share does.
# shellcheck disable=2115
{
    rm -rf "$1/etc"
    rm -rf "$1/usr/share"
    rm -rf "$1/usr/lib"
    rm -rf "$1/usr/include"
}
