#!/bin/sh -e

patch -p1 < no-uuid.patch

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddep11=false \
    -Dstemmer=false \
    -Dintrospection=false \
    -Drpm=false \
    . output

ninja -C output
ninja -C output install
